"use client";

import { useRouter } from 'next/navigation';
import { ArrowLeft, ScrollText } from 'lucide-react';

export default function TermsAndConditions() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-[#040A15] text-slate-200 font-sans selection:bg-[#004AAD]/50">

      {/* Header */}
      <header className="sticky top-0 z-20 px-4 sm:px-6 py-3 sm:py-4 bg-[#040A15]/95 backdrop-blur-md border-b border-white/[0.06]">
        <div className="max-w-3xl mx-auto flex items-center gap-3">
          <button
            onClick={() => router.push('/')}
            className="flex items-center justify-center w-8 h-8 rounded-lg text-slate-400 hover:text-white hover:bg-white/5 transition-colors flex-shrink-0"
            aria-label="Back to home"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <img src="/logo.png" alt="The Geostrata Logo" className="h-7 sm:h-9 w-auto object-contain" />
          <div className="h-6 w-px bg-white/15" />
          <div>
            <h1 className="text-[12px] sm:text-[14px] font-bold tracking-widest text-white uppercase leading-none mb-0.5">STRATA GPT</h1>
            <p className="text-[9px] sm:text-[10px] text-[#4D8BFF] font-semibold tracking-wider uppercase leading-none">Intelligence Engine</p>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-14">

        {/* Title block */}
        <div className="flex items-center gap-4 mb-10">
          <div className="w-10 h-10 rounded-xl bg-[#004AAD]/20 border border-[#004AAD]/30 flex items-center justify-center flex-shrink-0">
            <ScrollText className="w-5 h-5 text-[#4D8BFF]" />
          </div>
          <div>
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Terms & Conditions</h2>
            <p className="text-sm text-slate-500 mt-0.5">The Geostrata Foundation · Effective: June 9, 2025 · Last Updated: June 9, 2026</p>
          </div>
        </div>

        <div className="space-y-8 text-[15px] leading-[1.8] text-slate-300">

          <Section title="1. Acceptance of Terms">
            By accessing or using STRATA GPT at stratagpt.thegeostrata.com ("the Platform"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to these Terms, please do not use the Platform.
          </Section>

          <Section title="2. About the Platform">
            STRATA GPT is an AI-powered geopolitical intelligence engine developed and operated by The Geostrata Foundation. It provides users with analysis, information, and insights on geopolitical, policy, and international affairs topics.
          </Section>

          <Section title="3. Eligibility">
            You must be at least 13 years of age to use this Platform. By using STRATA GPT, you represent that you meet this requirement. If you are under 18, you should use the Platform only with the consent of a parent or guardian.
          </Section>

          <Section title="4. User Accounts and Authentication">
            <BulletList items={[
              'Access to STRATA GPT requires authentication via Google Sign-In.',
              'You are responsible for maintaining the confidentiality of your account.',
              'You agree to provide accurate and complete information during sign-in.',
              'We reserve the right to suspend or terminate accounts that violate these Terms.',
            ]} />
          </Section>

          <Section title="5. Acceptable Use">
            You agree to use STRATA GPT only for lawful purposes. You must not:
            <BulletList items={[
              'Use the Platform to generate, distribute, or promote unlawful, harmful, defamatory, or offensive content',
              'Attempt to reverse engineer, hack, or disrupt the Platform or its underlying systems',
              'Use automated scripts or bots to access the Platform beyond normal usage',
              'Impersonate any person, organisation, or entity',
              'Use the Platform to spread misinformation or propaganda',
              'Attempt to extract, scrape, or reproduce the Platform\'s underlying data or AI outputs at scale',
            ]} />
          </Section>

          <Section title="6. AI-Generated Content Disclaimer">
            <div className="bg-[#004AAD]/10 border border-[#004AAD]/25 rounded-xl px-5 py-4 space-y-2 text-slate-300">
              <BulletList items={[
                'Responses generated by STRATA GPT are produced by an AI system and are intended for informational purposes only.',
                'The Geostrata Foundation does not guarantee the accuracy, completeness, or timeliness of any AI-generated response.',
                'Nothing on this Platform constitutes legal, financial, medical, or professional advice.',
                'Users should independently verify any information before relying on it for decisions.',
              ]} />
            </div>
          </Section>

          <Section title="7. Intellectual Property">
            <BulletList items={[
              'All content, branding, design, and underlying technology of STRATA GPT is the intellectual property of The Geostrata Foundation.',
              'You may not reproduce, distribute, or commercially exploit any part of the Platform without prior written permission.',
              'AI-generated responses provided to you during your session may be used for personal, non-commercial reference only.',
            ]} />
          </Section>

          <Section title="8. Rate Limiting and Fair Use">
            To ensure fair access for all users, the Platform enforces rate limits on message volume. Excessive or abusive usage may result in temporary or permanent suspension of access.
          </Section>

          <Section title="9. Limitation of Liability">
            To the fullest extent permitted by applicable law:
            <BulletList items={[
              'The Geostrata Foundation shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform.',
              'Our total liability to you for any claim arising out of or relating to these Terms shall not exceed INR 1,000.',
            ]} />
          </Section>

          <Section title="10. Indemnification">
            You agree to indemnify and hold harmless The Geostrata Foundation, its founders, directors, and team members from any claims, damages, or expenses arising from your use of the Platform or violation of these Terms.
          </Section>

          <Section title="11. Termination">
            We reserve the right to suspend or terminate your access to STRATA GPT at any time, with or without notice, if we believe you have violated these Terms or applicable law.
          </Section>

          <Section title="12. Governing Law and Jurisdiction">
            These Terms are governed by the laws of India. Any disputes arising from these Terms or your use of the Platform shall be subject to the exclusive jurisdiction of the courts located in New Delhi, India.
          </Section>

          <Section title="13. Changes to Terms">
            We may revise these Terms at any time. Updated Terms will be posted on this page with a revised "Last Updated" date. Continued use of the Platform after changes constitutes your acceptance of the new Terms.
          </Section>

          <Section title="14. Contact Us">
            <div className="bg-[#0B1221] border border-slate-800 rounded-xl px-5 py-4 space-y-1">
              <p className="text-white font-semibold">The Geostrata Foundation</p>
              <p>Email: <a href="mailto:techatgeostrata@gmail.com" className="text-[#4D8BFF] hover:underline">techatgeostrata@gmail.com</a></p>
              <p>Website: <a href="https://thegeostrata.com" target="_blank" rel="noopener noreferrer" className="text-[#4D8BFF] hover:underline">thegeostrata.com</a></p>
            </div>
          </Section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/[0.06] px-4 sm:px-6 py-6 mt-10">
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="text-xs text-slate-600">© {new Date().getFullYear()} The Geostrata Foundation. All rights reserved.</p>
          <div className="flex items-center gap-4 text-xs">
            <a href="/privacy-policy" className="text-slate-500 hover:text-slate-300 transition-colors">Privacy Policy</a>
            <span className="text-slate-700">·</span>
            <a href="/terms" className="text-[#4D8BFF]">Terms & Conditions</a>
          </div>
        </div>
      </footer>

    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="border-t border-white/[0.06] pt-8">
      <h3 className="text-[17px] sm:text-[18px] font-semibold text-white mb-3">{title}</h3>
      <div className="text-slate-400">{children}</div>
    </div>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="space-y-1.5 mt-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2.5">
          <span className="mt-2 w-1 h-1 rounded-full bg-[#4D8BFF] flex-shrink-0" />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}